### ISSUE TITLE
should escalate remove an event from the inbox?

### ISSUE THREAD

**Issue by inliniac** [jasonish/evebox#23]
When going through the inbox I tend to either 'archive' (event isn't interesting), or 'escalate' (lets look at it later). I wonder if it makes sense if the latter would also remove it from the inbox.

Or perhaps an 'escalate and archive' button would do. Archived events that are escalated are still accessible in the 'escalated' pane.

**Comment by jasonish** [comment]
If you look at the help you'll see F9 - Escalate and archive event...  Well it turns out I put it in the help but never implemented.  So its done now.

My intention is that clicking the "*" leaves it in the inbox, like Gmail.  I could add a button the drop down for escalate and archive for non-keyboard users.

**Comment by jasonish** [comment]
I addition to the shortcut, I've now added a button as well.
