### ISSUE TITLE
Using additional-fields as filters ?

### ISSUE THREAD

**Issue by malexe3169** [jasonish/evebox#281]
Is it possible to use the additional-fields as filters ?

I've added the additional-field and it work I see in the data, but I am not able to filter with it.

**Comment by jasonish** [comment]
This *should* work, but due to escaping and what characters you choose it is possible I break something along the query path:
- what is your custom fields name and value (or something a close approximation in terms of character set)
- are you adding this with the agent or the server
- elasticesearch?

**Comment by malexe3169** [comment]
It is added with the agent, with the evebox-agent.yaml like this:

additional-fields:
  sensor-name: "LLLL-LLL-NN"

L = Letters
N = Numbers

using opensearch 2.8.0

**Comment by jasonish** [comment]
Try this in the search box:
```
sensor-name.keyword:"AAAA-BBB-12"
```

I think what Elasticsearch does is analyzes/tokenizes the value and that is what you are searching again with just `sensor-name`, however, this often doesn't work for exact matches which the `.keyword` will work for.  Internally Elasticsearch has a table of fields where the keyword variant needs to be used to hide most uses of this.

**Comment by malexe3169** [comment]
it works, thank you very much!
