### ISSUE TITLE
Send evebox events to ELK on cutom index 

### ISSUE THREAD

**Issue by mynaxyss** [jasonish/evebox#78]
Hello,

I have a problem, ican't send evebox events on ELK custom index.
by default the events are indexed on logstash index and when i specify custom index with option -i the event are not send.
example:   **evebox -v -e http://localhost:9200 --input /var/log/suricata/eve.json -i evebox**

thanks in advance for your replay

**Comment by demospace** [comment]
It looks like the -i feature (and the "index:" option in yml) doesn't use the name unaltered -- it assumes the index name is a prefix and appends a "-"

So if you give it "-i suricata_0" it's actually using "suricata_0-*" and similar.

I dropped by to create this as an issue because not all of us use prefixes in that way. That's likely the issue you're seeing.

**Comment by jasonish** [comment]
Closing this issue as I cannot replicate it.

One thing to note is that when EveBox is indexing events into Elastic Search itself it does so in the same as as a default Logstash installation would.  If you set the index to be "evebox" it will actually created indexes like evebox-YYYY.MM.DD and so on.
